apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: kodekloud-kub-course-oct-18
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: kodekloud-kub-course-oct-18
  template:
    metadata:
      name: postgress-pod
      labels:
        name: postgress-pod
        app: kodekloud-kub-course-oct-18
    spec:
      containers:
      - name: postgress
        image: postgress:9.4
        ports:
        - containerPort: 5432
