apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: kodekloud-kub-course-oct-18
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-pod
    app: kodekloud-kub-course-oct-18
